### ISSUE TITLE
Input Source

### ISSUE THREAD

**Issue by chenhsi** [chenhsi/Ambroscum#22]
Presumably, there should be some way of acquiring input of some sort, or else all of the programs would be deterministic (barring a source of random data, which is also a good idea for a built-in library); compiling would simply be evaluating and saving the output.

This input might be in the form of direct user input (e.g. command line) or through other I/O means (e.g. reading from/writing to a file).

**Comment by edgao** [comment]
"ghost assigned edgao"

well ok then
